### ISSUE TITLE
复现时出现的问题

### ISSUE THREAD

**Issue by duanruixia** [YetZzzzzz/GLoMo#2]
作者您好，我在复现的时候出现了这个问题，是因为我下的包的问题吗，您requirements中的包，我并没有全下完，我是直接运行，看它缺哪个包，我再去下您对应版本的包，这会是我出现问题的原因吗
![微信图片_20241219195437](https://github.com/user-attachments/assets/c487e74a-8993-4d6c-8bb9-707dc6aa5643)

**Comment by YetZzzzzz** [comment]
您好，这好像不是包的问题，是维度的问题。MOSI和MOSEI两个数据集的VISUAL_DIM是不一样的，一个是35，一个是47。您要不检查下这个问题呢

**Comment by duanruixia** [comment]
感谢您的解答，可能是因为服务器的问题，不知道为啥，一下子跑起来了，可能会有点冒昧，mosi复现出的结果离您在论文中公布的结果有些差异，差了有三个多点，大概率是我的问题，但还是希望您能帮忙解答一下

**Comment by duanruixia** [comment]
感谢您的解答，我已经解决这个问题了
